// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sdconeomirusjgjswtog.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNkY29uZW9taXJ1c2pnanN3dG9nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYzMDI1NjYsImV4cCI6MjA3MTg3ODU2Nn0.5WafqXq1wJmON1s7kbWLwHxTxUs-F8XPXScYGZPBEl0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});